name: ntt_atom_flutter
description: A Flutter SDK for integrating NTT Atom Pay, enabling seamless payment processing with secure and efficient transactions.
repository: https://github.com/gktirkha/ntt_atom_flutter.git
homepage: https://github.com/gktirkha/ntt_atom_flutter
version: 0.0.1

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.6
  cryptography: ^2.7.0
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  freezed_annotation: ^2.4.4
  http: ^1.3.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_serializable: ^6.9.4

platforms:
  ios:
  android:
